Clase del 04 de marzo de 2021
agarbuno/aprendizaje-estadistico pull request #16
Opened 2021-03-05 03:44 UTC by MajoSedCast

2021-03-19 17:48 UTC, agarbuno requested changes
Hola @MajoSedCast , ¿podrías cambiar el nombre por el número de clase que te tocó?

2021-03-19 17:49 UTC, agarbuno requested changes
Por cierto, el archivo está vacío.

2021-03-20 18:08 UTC, MajoSedCast reviewed
Hola profe, no sé qué está pasando me sigue apareciendo archivo vacío, mandé el pdf a mis compañeros donde vamos subiendo todos los pdf también se lo adjunto, quedo atenta, opté por copiar y pegar pero no funciona tampoco.

2021-03-20 18:16 UTC, MajoSedCast reviewed
[lecture_14.pdf](https://github.com/agarbuno/aprendizaje-estadistico/files/6176144/lecture_14.pdf)

2021-05-27 19:12 UTC, merged